# Generated by Django 6.0.1 on 2026-02-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clave', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('coste_lanzamiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='espacio.agencia')),
            ],
        ),
    ]
